### ISSUE TITLE
Utworzenie bazowej solucji

### ISSUE THREAD

**Issue by kotulskidamian** [kkms30/SmartShop#10]
SP: 1
Jako developer chcę mieć utworzoną solucję w Visual Studio, zawierającą puste projekty utworzone w odpowiednich/wybranych technologiach

KA: bazowa solucja dołączona do repozytorium

**Comment by kurkiewiczkrzysztof** [comment]
Bazowe solucje do projektu zostaly utworzone w repozyterium, oraz pobrane przez uzytkownikow
