### ISSUE TITLE
Zwrot produktów.

### ISSUE THREAD

**Issue by kotulskidamian** [kkms30/SmartShop#103]
SP: 3
Jako developer chcę mieć możliwość zwrócenia przedmiotu z danej transakcji, abym mógł obsłużyć przypadek reklamacji/zwrotu produktów przez nabywce.

KA: wyszukanie konkretnej transakcji po wpisaniu jej id w pole "Wyszukaj" w zakładce "Zwroty", możliwość zaznaczenia i zwrócenia produktu po naciśnięciu przycisku "Zwróć", synchronizacja z bazą danych, projekt się kompiluje.

**Comment by kkms30** [comment]
Zadanie zostało ukończone.
