### ISSUE TITLE
Zwrot produktów na paragonie.

### ISSUE THREAD

**Issue by kotulskidamian** [kkms30/SmartShop#104]
SP: 3
Jako developer chcę mieć możliwość pokazania na paragonie informacji na temat zwróconych produktów, abym mógł tworzyć paragony dla aktualnego stanu danej transakcji.

KA: po zwróceniu przedmiotu w danej transakcji jest możliwość stworzenia paragonu zawierającego informację o zwróconych produktach, projekt się kompiluje.

**Comment by kkms30** [comment]
Zadanie zostało ukończone.
