### ISSUE TITLE
Ceny produktów.

### ISSUE THREAD

**Issue by kotulskidamian** [kkms30/SmartShop#109]
SP: 2
Jako developer chcę mieć poprawione ceny produktów dostępne w aplikacji, tak aby były one bardziej rzeczywiste.

KA: nowe ceny produktów w bazie, w granicach od 10 do 400 zł, dwa miejsca po przecinku

**Comment by Tomciu** [comment]
Ogarnięte.
Zmieniono typ danych tabeli Products z FLOAT na DECIMAL dodając dwa miejsca po przecinku.
Zaktualizowano wszystkie rekordy w tabeli Products na losową wartość pomiędzy 10 a 400 (z uwzględnieniem dwóch miejsc po przecinku) wykorzystując do tego zapytanie: update Products set Price = (RAND() * (400 - 10 + 1)) + 10;

**Comment by kotulskidamian** [comment]
Ok.
