### ISSUE TITLE
Architektura i specyfikacja projektu

### ISSUE THREAD

**Issue by kotulskidamian** [kkms30/SmartShop#11]
SP:
Jak developer chcę mieć dokument zawierający wstępne założenia projektu, diagram klas, wykorzystywane technologie 
oraz scenariusz z przypadkami użycia abym mógł na ich podstawie rozpocząć rozwój projektu

KA: dokument opisujący specyfikację projektu dołączony do repozytorium

**Comment by GrzegorzKatze** [comment]
Jeżeli coś zostało dodane do sprintu. Jest już w "TODO" sprintu. Nie należy usuwać tego zadania. 

1. Jeżeli tak jak w tym przypadku zadanie jest duplikatem, a juz znajduje się w sprincie należy re-estymować zadanie na 0 punktów i dać je na "done".

**Comment by kotulskidamian** [comment]
Ok, dziękujemy, będziemy pamiętać.

W dniu 31 marca 2017 07:24 użytkownik GrzegorzKatze <
notifications@github.com> napisał:
