### ISSUE TITLE
Poprawa widoku głównego.

### ISSUE THREAD

**Issue by kotulskidamian** [kkms30/SmartShop#110]
SP: 2
Jako developer chcę mieć poprawiony widok i logikę aplikacji aby był on bardziej odporny na błędy.

KA: brak możliwości wpisania liter do ilości zakupionego produktu, blokowanie pozostałych zakładek po dodaniu kodu do zakładki "Kod ręcznie", usunięte checkboxy na widoku nowej transakcji, projekt się kompiluje.

**Comment by kkms30** [comment]
Zadanie zostało ukończone.
