### ISSUE TITLE
Poprawa widoku obecnej transakcji.

### ISSUE THREAD

**Issue by kotulskidamian** [kkms30/SmartShop#124]
SP: 1
Jako developer chcę mieć poprawiony widok obecnie przeprowadzanej transakcji, tak aby wszystkie informacje były widoczne, bez konieczności przewijania paska dolnego.

KA: projekt się kompiluje, kolumny zawierające informacje o transakcji odpowiednio zmienione.

**Comment by kkms30** [comment]
Zadanie zostało ukończone.
