### ISSUE TITLE
"Drukowanie" podsumowań

### ISSUE THREAD

**Issue by kotulskidamian** [kkms30/SmartShop#128]
SP: 3
Jako developer chcę mieć możliwość wygenerowania pdf'a z informacjami o podsumowaniach, tak abym mógł "drukować" podsumowanie dnia i miesiąca.

KA: Dodanie przycisków "Podsumowanie dnia" i "Podsumowanie miesiąca" i zakładce "Raporty", generujący się plik .pdf dla podsumowania dnia i miesiąca

**Comment by kkms30** [comment]
Zadanie zostało ukończone.
