### ISSUE TITLE
Obsługa płatności.

### ISSUE THREAD

**Issue by kotulskidamian** [kkms30/SmartShop#129]
SP: 3
Jako developer chcę mieć stworzone nowe okno płatności, abym mógł zapłacić za transakcję kartą lub gotówką.

KA; Otwierające się okno z wyborem płatności po kliknięciu przycisku "Płatność, możliwość zapłaty kartą i gotówką, projekt się kompiluje.

**Comment by kkms30** [comment]
Zadanie zostało ukończone.
