### ISSUE TITLE
Utworzenie webservicu

### ISSUE THREAD

**Issue by kotulskidamian** [kkms30/SmartShop#16]
SP: 1
Jako developer chcę mieć utworzony webservice abym mógł komunikować się z nim z aplikacji klienckiej

KA: możliwość wykonania metod HTTP dla każdej z tabeli i uzyskanie prawidłowej odpowiedzi, projekt się kompiluje

**Comment by kotulskidamian** [comment]
WebService został utworzony. Dodatkowo do projektu został dołączony dokument opisujący dostępne metody i endpointy. Zostały przeprowadzone testy przez narzędzie Postman.

**Comment by kurkiewiczkrzysztof** [comment]
Projekt kompiluje się oraz zawiera odpowiednie kontrolery. Potrzebne dla projektu metody http działają i zwracają wartości odpowiednie dla swoich kontrolerów.
