### ISSUE TITLE
Zabezpieczenie brancha develop

### ISSUE THREAD

**Issue by kotulskidamian** [kkms30/SmartShop#19]
SP: 1
Jako developer chcę mieć zmodyfikowane ustawienia brancha develop, aby konieczne było wykonanie review przed commitem/mergem

KA: zablokowana możliwość commitowania/mergowania do brancha develop, bez wcześniejszego wykonania rewiew

**Comment by kkms30** [comment]
Wprowadziłem zmiany zgodne treścią taska. Przy próbie commita/merge do brancha develop bez wcześniejszego rewiew kończy się błędem:
remote: error: GH006: Protected branch update failed for refs/heads/develop.        
remote: error: At least one approved review is required

**Comment by kotulskidamian** [comment]
Wprowadziłem zmiany zgodne treścią taska. Próba commita/merge do brancha develop bez wcześniejszego rewiew kończy się błędem:
remote: error: GH006: Protected branch update failed for refs/heads/develop.
remote: error: At least one approved review is required

**Comment by kurkiewiczkrzysztof** [comment]
Branch develop został zabezpieczony, nie ma możliwości wprowadzania zmian na nich bez uprzedniego wykonania review
