### ISSUE TITLE
Kategoria produktu w bazie danych

### ISSUE THREAD

**Issue by kotulskidamian** [kkms30/SmartShop#22]
SP: 1
Jako developer chcę mieć zmodyfikowaną bazę danych, abym mógł przechowywać w niej informacje na temat kategorii danego produktu

KA: możliwość przechowywania informacji o kategorii produktu w bazie danych

**Comment by Tomciu** [comment]
Dodano dodatkową tabele "categories", która przechowuje nazwy kategorii produktów.
Łączenie:
categories 1 : n products
categories 1: 1 orderdetails

**Comment by Tomciu** [comment]
Zmieniono sposób przechowywania informacji o kategoriach produktów. Od teraz tabela Categories jest podłączona bezpośrednio i tylko do tabeli Products. 
Dodano łączenie n : n pomiędzy Transactions i Orders w celu umożliwienia łączenia jednej transakcji do wielu zamówień. 
Poprawiono zapis kluczy obcych w bazie na bardziej czytelne, skrócono ich nazwy do bardziej przystępnych.
Poprawiono nazwy tabel w bazie danych na bardziej opisujące to jakie dane w niej się znajdują.

**Comment by kotulskidamian** [comment]
Po zmianach wszystko ok, można przechowywać informację w o kategorii produktu w bazie, relacje między tabelami w porządku.
