### ISSUE TITLE
Zdjęcie produktu w bazie danych

### ISSUE THREAD

**Issue by kotulskidamian** [kkms30/SmartShop#23]
SP: 1
Jako developer chcę mieć zmodyfikowaną bazę danych, abym mógł przechowywać w niej zdjęcie danego produktu

KA: pole w bazie danych przechowujące zdjęcie produktu

**Comment by Tomciu** [comment]
Dodano nową kolumnę w tabeli "products" o nazwie "image" i typie MEDIUMBLOB. Pozwoli ona nam do przechowywania zdjęcia produktu w formie binarnej o wielkości nie większej niż ~16mb

**Comment by kotulskidamian** [comment]
Pole 'image' zostało prawidłowo dodane do bazy
