### ISSUE TITLE
Stworzenie schematu bazy danych

### ISSUE THREAD

**Issue by kotulskidamian** [kkms30/SmartShop#4]
SP: 2
Jako developer chce mieć utworzony schemat bazy danych na podstawie którego będę w stanie wygenerować tabele.

KA: kod SQL tworzący tabele w bazie danych

**Comment by kkms30** [comment]
Kod SQL wygenerowany poprawnie.

**Comment by kotulskidamian** [comment]
Schemat bazy utworzony poprawnie, kod SQL pozwolił wygenerować tabele w bazie.
