### ISSUE TITLE
Projekt z testami jednostkowymi

### ISSUE THREAD

**Issue by kotulskidamian** [kkms30/SmartShop#51]
SP: 1
Jako developer chce mieć utworzony projekt z odpowiednio skonfigurowanymi bibliotekami abym mógł tworzyć w nim testy jednostkowe dla aplikacji

KA: kompilujący się projekt dodany do repozytorium, zawierający bibliotekę NUnit, bibliotekę pozwalającą tworzyć adaptery i mocki

**Comment by kurkiewiczkrzysztof** [comment]
Ważna informacja oprócz powyższego commita. Utworzono także dwa foldery Webapp.Tests gdzie nalezy dodawac testy projektu SmartShopWebApp, oraz folder Wpf.Tests, gdzie należy dodawać testy projektu SmartShopWpf. Dodawanie testu: PPM->Add->New Item->Wybieramy Test po lewej->Wybieramy Basic Unit Test, albo Unit Test. Róznica: Unit Test wspiera ClassInitialize, ClassCleanUp, TestInitialize oraz TestCleanup, które pozwalają na wykonanie troche kodu przed/po test fixture, oraz przed/po każdemu UnitTestowi. Jeśli nie potrzebujemy tego, wystarczy stworzyc Basic Unit Test.
