### ISSUE TITLE
Wylogowanie z aplikacji

### ISSUE THREAD

**Issue by kotulskidamian** [kkms30/SmartShop#53]
SP: 1
Jako developer chce po móc wylogować się z aplikacji po naciśnięciu przycisku wyloguj, abym mógł zmieniać obsługującego kasę kasjera

KA: projekt się kompiluje, zamknięcie widoku głównego i uruchomienie widoku logowania po kliknięciu przycisku "wyloguj"

**Comment by kurkiewiczkrzysztof** [comment]
Przepraszam za wykonanie issue przed przeniesieniem Taska i zapisaniem sie do niego

**Comment by kotulskidamian** [comment]
Wykonane poprawnie.
