### ISSUE TITLE
Przekazanie danych pomiędzy widokami

### ISSUE THREAD

**Issue by kotulskidamian** [kkms30/SmartShop#55]
SP: 1
Jako developer chce mieć zaimplementowaną możliwość przekazania danych z widoku logowania do widoku głównego, abym mógł wyświetlić w widoku głównym informacje o zalogowanym kasjerze i wykorzystywanej kasie

KA: projekt się kompiluje, wyświetlenie na widoku głównym numeru identyfikacyjnego zalogowanego kasjera i wykorzystywanej kasy

**Comment by kotulskidamian** [comment]
Utworzono mechanizm pozwalający przechowywać informacje o zalogowanym kasjerze, wykorzystywanej kasie i dostępnych produktach przez cały czas jednego uruchomienia aplikacji. Zaimplementowano wyświetlanie numeru kasjera, kasy i daty w głównym widoku aplikacji.

**Comment by Tomciu** [comment]
Wszystko w porządku.
