### ISSUE TITLE
Zabezpieczenie dostępu do usług Web Servicu

### ISSUE THREAD

**Issue by kotulskidamian** [kkms30/SmartShop#57]
SP: 3
Jako developer chcę mieć zaimplementowaną funkcjonalność umożliwiającą dostęp do usług tylko dla zalogowanych kasjerów, tak abym mógł chronić dane przed nieupoważnionymi osobami

KA: posiadanie dostępu do usług tylko dla zalogowanych, do systemu, kasjerów (oprócz usługi logującej), projekt się kompiluje

**Comment by kotulskidamian** [comment]
Korzystanie z usług Web Service'u zostało domyślnie zablokowane. Wymagany jest token podawany w nagłówku http podczas zapytania.

**Comment by Tomciu** [comment]
Wszystko w porządku.
