### ISSUE TITLE
Logowanie w module odpowiedzialnym za komunikację z Web Servicem

### ISSUE THREAD

**Issue by kotulskidamian** [kkms30/SmartShop#59]
SP: 2
Jako developer chcę mieć zaimplementowaną funkcjonalność komunikacji z Web Servicem w kwestii logowania, tak abym mógł przesłać dane kasjera do Web Servicu i otrzymać odpowiedź czy dane są poprawne

KA: w projekcie służący do obsługi Web Servicu, utworzone klasy/metody pozwalające przesłać dane logującego się kasjera i przetworzyć odpowiedź, projekt się kompiluje

**Comment by kotulskidamian** [comment]
W module odpowiedzialnym za komunikację zostały utworzone metody do pozyskiwania tokenu i logowania kasjera. Komunikacja z Web Servic'em odbywa się z wykorzystaniem biblioteki RestSharp.

**Comment by Tomciu** [comment]
Wszystko w porządku.
