### ISSUE TITLE
Wyświetlenie dostępnych produktów w aplikacji

### ISSUE THREAD

**Issue by kotulskidamian** [kkms30/SmartShop#61]
SP: 2
Jako developer chcę mieć pokazane w zakładce "Kod z listy" wszystkie produkty dostępne w systemie, abym mógł dodawać je do transakcji

KA: wyświetlone wszystkie produkty dostępne w systemie w zakładce "Kod z listy" w widoku głównym aplikacji, projekt się kompiluje

**Comment by kotulskidamian** [comment]
Dodano wyświetlanie numeru, nazwy, ceny i kategorii produktu w zakładce "kod z listy" w widoku głównym aplikacji.

**Comment by Tomciu** [comment]
Wszystko w porządku.
