### ISSUE TITLE
Mock kategorii

### ISSUE THREAD

**Issue by kotulskidamian** [kkms30/SmartShop#62]
SP: 1
Jako developer chcę mieć pokazane kategorie produktów dostępnych w systemie, abym mógł w przyszłości sortować produkty w zależności od kategorii

KA: wpisane "na sztywno" i pokazane dostępne kategorie w systemie na głównym widoku aplikacji, projekt się kompiluje

**Comment by kotulskidamian** [comment]
Wszystko ok.

**Comment by kkms30** [comment]
Działa poprawnie.
