### ISSUE TITLE
Backlog produktu

### ISSUE THREAD

**Issue by kotulskidamian** [kkms30/SmartShop#7]
SP: 1
Jako developer chcę mieć arkusz Excel w którym będę mógł utrzymywać historię rozwoju produktu oraz planować taski na kolejne sprinty

KA: backlog produktu w excelu dołączony do repozytorium

**Comment by kurkiewiczkrzysztof** [comment]
Posiadamy w repozytorium arkusz Excela, w którym mozemy planowac taski oraz utrzmywac historie rozwoju produktu
