### ISSUE TITLE
Konfiguracja i wdrożenie w gita

### ISSUE THREAD

**Issue by kotulskidamian** [kkms30/SmartShop#8]
SP: 2
Jako developer chcę:
- mieć utworzone i skonfigurowane repozytorium git
- mieć utworzone i odpowiednio podzielone branche
- aby pozostali członkowie zespołu potrafili obsługiwać podstawowe operacje

abym mógł utrzymywać kod na zdalnym repozytorium i kontrolować jego wersje

KA: utworzone branche w zdalnym repozytorium git: master, develop, zablokowany dostęp do mastera, develop jako branch domyślny

**Comment by kurkiewiczkrzysztof** [comment]
Brahcne master,develop,zablokowany dostep do mastera oraz develop jako domyslny zostaly poprawnie utworzone. Teraz jako developer pracuje w teamie który zna gita i wykonuje na nim podstawowe operacje oraz mam dostep do branchy.
