### ISSUE TITLE
Ukryte znaki przy wpisywaniu hasła.

### ISSUE THREAD

**Issue by kotulskidamian** [kkms30/SmartShop#83]
SP: 1
Jako developer chcę mieć ukryte znaki podczas wpisywania hasła, aby hasło nie było widoczne podczas wpisywania dla osób nieupoważnionych.

KA: ukryty każdy pojedynczy znak wpisywany z klawiatury w pole hasła, projekt się kompiluje.

**Comment by kkms30** [comment]
Działa poprawnie.
