### ISSUE TITLE
Wpisywanie kodu z klawiatury.

### ISSUE THREAD

**Issue by kotulskidamian** [kkms30/SmartShop#84]
SP: 1
Jako developer chcę mieć możliwość wpisania kodu z klawiatury, abym mógł dodawać produkty do transakcji gdy znam odpowiedni kod.

SP: możliwość wpisania kodu produktu w zakładce "Kod ręcznie" na głównym widoku, projekt się kompiluje.

**Comment by kotulskidamian** [comment]
Wszystko ok.

**Comment by kkms30** [comment]
Działa poprawnie.
