### ISSUE TITLE
Dodanie produktu do transakcji - "Kod ręcznie"

### ISSUE THREAD

**Issue by kotulskidamian** [kkms30/SmartShop#86]
SP: 5
Jako developer chcę mieć możliwość dodania produktu do transakcji, abym następnie mógł obsłużyć płatność i generować paragony.

KA: w zakładce "Kod ręcznie" na głównym widoku - dodawanie wybranego produktu/produktów do transakcji po wpisaniu prawidłowego kodu, naciśnięciu przycisku "Dodaj", projekt się kompiluje.

**Comment by kkms30** [comment]
Działa poprawnie.
