### ISSUE TITLE
Wyświetlanie bieżącej ceny łącznej zakupów.

### ISSUE THREAD

**Issue by kotulskidamian** [kkms30/SmartShop#87]
SP: 1
Jako developer chcę mieć pokazaną i uaktualnianą na bieżąco cenę łączną wszystkich produktów, abym mógł następnie na jej podstawie generować paragon.

KA: uaktualniana na bieżąco cena produktu podczas dodawania go do transakcji - wyświetlana na głównym widoku aplikacji, projekt się kompiluje.

**Comment by kkms30** [comment]
Działa poprawnie.
