### ISSUE TITLE
Transakcja.

### ISSUE THREAD

**Issue by kotulskidamian** [kkms30/SmartShop#88]
SP: 3
Jako developer chcę mieć zaimplementowany mechanizm tworzenia transakcji i dodawania ich do bazy, abym mógł dokonać zakupu przedmiotów i przechowywać informacje o nich.

KA: wygenerowanie i pokazanie numeru transakcji na widoku głównym po dodaniu do transakcji pierwszego produktu, możliwość dodania i przechowywania informacji o transakcji w bazie, projekt się kompiluje.

**Comment by kkms30** [comment]
Działa poprawnie.
